/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-icons.html
 */

/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../iron-iconset-svg/iron-iconset-svg.d.ts" />

/**
 * *Note:** This is closed software and you can't use it in your projects unless
 * you are a Mulesoft employee working on internall project.
 *
 * A set of Anypoint icons to be used with ARC web components.
 * They occupy the same namespace as ARC icons set.
 *
 * Use them in bower.json like this:
 *
 * ```
 * "dependencies": {
 *   ...
 *   "arc-icons": "advanced-rest-clinet/anypoint-icons"
 * }
 * ```
 * Be sure to put it to the end of the dependencies so it won't be replaced with original
 * ARC icons by other comnponent.
 *
 * Include library into the document / element:
 * ```
 * <link rel="import" href="../arc-icons/arc-icons.html">
 * ```
 *
 * To use an icon from this set you should prefix `iron-icon` with the `arc`, followed by a colon, ":", and then the icon id.
 *
 * Example using the directions-bus icon from the maps icon set:
 * ```
 * <iron-icon icon="arc:add"></iron-icon>
 * ```
 */
interface AnypointIconsElement extends Polymer.Element {
}

interface HTMLElementTagNameMap {
  "anypoint-icons": AnypointIconsElement;
}
